- name: ensure package and workspace directory exists
  file:
    path: "{{item}}"
    state: directory
    mode: 0755
    recurse: yes
  loop:
    - "{{ketadb_node_workspace}}/files"
    - "{{ketadb_node_workspace}}/{{ketadb_version}}"

- name: copy package file to remote package directory
  copy:
    src: "{{ketadb_file}}"
    dest: "{{ketadb_node_workspace}}/files/keta-{{ketadb_version}}.tar.gz"

- name: untar package file to workspace
  unarchive:
    src: "{{ketadb_node_workspace}}/files/keta-{{ketadb_version}}.tar.gz"
    dest: "{{ketadb_node_workspace}}/{{ketadb_version}}"
    extra_opts: "--strip-components=1"
    remote_src: yes
    creates: "{{ketadb_node_workspace}}/{{ketadb_version}}/keta_manifest"

- name: copy config/keta.yml
  template:
    src: keta.yml.j2
    dest: "{{ketadb_node_workspace}}/{{ketadb_version}}/config/keta.yml"

- name: copy config/jvm.options
  template:
    src: jvm.options.j2
    dest: "{{ketadb_node_workspace}}/{{ketadb_version}}/config/jvm.options"

- name: copy supervisor.conf
  template:
    src: supervisor.conf.j2
    dest: "/home/{{ketadb_user}}/supervisor/conf.d/ketadb_{{ketadb_node_config['node.name']}}.conf"

- name: replace current ketadb home
  file:
    src: "{{ketadb_node_workspace}}/{{ketadb_version}}"
    dest: "{{ketadb_node_workspace}}/main"
    state: link