- name: Stop ketadb - {{ketadb_node_config['node.name']}}
  supervisorctl:
    name: ketadb_{{ketadb_node_config['node.name']}}
    state: stopped
    config: /home/{{ketadb_user}}/supervisor/supervisord.conf
    supervisorctl_path: /home/{{ketadb_user}}/.local/bin/supervisorctl

- name: Wait for stopping
  wait_for:
    port: "{{ketadb_node_config['transport.tcp.port']}}"
    timeout: 60
    state: drained
