- name: Ensure ksupervisor/conf.d exists
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ supervisor_run_user }}"
    group: "{{ supervisor_run_user }}"
    recurse: yes
  loop:
    - "/opt/ksupervisor"
    - "/opt/ksupervisor/conf.d"

- name: Copy Supervisor init file into place for supervisord
  become: yes
  template:
    src: supervisor.conf.j2
    dest: "{{ supervisor_conf_path }}"

- name: Copy Supervisor init file into place for systemd
  become: yes
  template:
    src: supervisord.service.j2
    dest: "/lib/systemd/system/ksupervisord.service"

- name: Ensure Supervisor is enabled at boot.
  become: yes
  systemd:
    name: ksupervisord
    enabled: yes
