- name: ketadb manager
  hosts: master
  user: keta
  vars:
    ketadb_run_user: keta
    ketadb_version: v1.2.2.1
    ketadb_install_file: /tmp/keta-v1.2.2.1-apps.tar.gz

    ketadb_heap_size: 1g
    ketadb_root_path: /opt/ketadb_master
    ketadb_supervisor_program: ketadb_master
    ketadb_supervisor_logfile: /tmp/supervisor-ketadb-master.log
    ketadb_config:
      http.port: 9200
      transport.tcp.port: 9300

      node.master: "true"
      node.web: "true"
      node.data: "false"

      discovery.zen.ping.unicast.hosts:
        - 127.0.0.1:9300
        - 127.0.0.1:9301
        - 127.0.0.1:9302

      keta.environment: "local"
      keta.database.mysql.url: "127.0.0.1:3306"
      keta.database.mysql.database: "ketadb"
      keta.database.mysql.user: "keta"
      keta.database.mysql.password: "123456"

      path.data: "../var/data"
      path.logs: "../var/logs"
  tasks:
    - name: install master ketadb
      include_role:
        name: ketadb
      tags:
        - install
        - restart
        - start
        - status
        - stop

- name: install web ketadb
  hosts: web
  user: keta
  vars:
    ketadb_run_user: keta
    ketadb_version: v1.2.2.1
    ketadb_install_file: /tmp/keta-v1.2.2.1-apps.tar.gz

    ketadb_heap_size: 1g
    ketadb_root_path: /opt/ketadb_web
    ketadb_supervisor_program: ketadb_web
    ketadb_supervisor_logfile: /tmp/supervisor-ketadb-web.log
    ketadb_config:
      http.port: 9201
      transport.tcp.port: 9301

      node.master: "false"
      node.web: "true"
      node.data: "false"

      discovery.zen.ping.unicast.hosts:
        - 127.0.0.1:9300
        - 127.0.0.1:9301
        - 127.0.0.1:9302

      keta.environment: "local"
      keta.database.mysql.url: "127.0.0.1:3306"
      keta.database.mysql.database: "ketadb"
      keta.database.mysql.user: "keta"
      keta.database.mysql.password: "123456"

      path.data: "../var/data"
      path.logs: "../var/logs"
  tasks:
    - name: install web ketadb
      include_role:
        name: ketadb
      tags:
        - install
        - restart
        - start
        - status
        - stop

- name: install data ketadb
  hosts: data
  user: keta
  vars:
    ketadb_run_user: keta
    ketadb_version: v1.2.2.1
    ketadb_install_file: /tmp/keta-v1.2.2.1-apps.tar.gz

    ketadb_heap_size: 2g
    ketadb_root_path: /opt/ketadb_data
    ketadb_supervisor_program: ketadb_data
    ketadb_supervisor_logfile: /tmp/supervisor-ketadb-data.log
    ketadb_config:
      http.port: 9202
      transport.tcp.port: 9302

      node.master: "false"
      node.web: "false"
      node.data: "true"

      discovery.zen.ping.unicast.hosts:
        - 127.0.0.1:9300
        - 127.0.0.1:9301
        - 127.0.0.1:9302

      keta.environment: "local"
      keta.database.mysql.url: "127.0.0.1:3306"
      keta.database.mysql.database: "ketadb"
      keta.database.mysql.user: "keta"
      keta.database.mysql.password: "123456"

      path.data: "../var/data"
      path.logs: "../var/logs"
  tasks:
    - name: install data ketadb
      include_role:
        name: ketadb
      tags:
        - install
        - restart
        - start
        - status
        - stop
