- name: Check if mysql is installed
  stat:
    path: "{{ mysql_root_path }}/install.tag"
  register: mysql_install_check

- name: Ensure mysql uninstall before install
  fail: msg="You must uninstall it before install."
  when: mysql_install_check.stat.exists

- name: Ensure no mysql running
  become: yes
  shell: >-
    ps -ef | grep -v grep | grep -w 'mysqld' | awk '{print $2}' | xargs kill -9 || echo 0

- name: Delete mysql data and logs directory
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ mysql_data_path }}"
    - "{{ mysql_logs_path }}"

- name: Ensure mysql data and logs directory exists
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ mysql_run_user }}"
    group: "{{ mysql_run_user }}"
    recurse: yes
  loop:
    - "{{ mysql_root_path }}"
    - "{{ mysql_data_path }}"
    - "{{ mysql_logs_path }}"

- name: Copy mysql install file into tmp directory
  copy:
    src: "{{ mysql_install_file }}"
    dest: "/tmp/ketadb-mysql.install.file"

- name: Unarchive mysql install file to workspace
  unarchive:
    src: "/tmp/ketadb-mysql.install.file"
    dest: "{{ mysql_root_path }}"
    extra_opts: "--strip-components=1"
    remote_src: yes
    creates: "{{ mysql_root_path }}/bin/mysqld"

- name: Touch the tag file for checking installed
  file:
    path: "{{ mysql_root_path }}/install.tag"
    state: touch
