- name: Start ketadb - mysql
  supervisorctl:
    name: "{{ mysql_supervisor_program }}"
    state: started
    config: "{{ supervisor_conf_path }}"
    supervisorctl_path: "{{ supervisor_bin_path }}/supervisorctl"

- name: Wait for mysql starting within 120s
  wait_for:
    port: "{{ mysql_run_port }}"
    timeout: 120