- name: Fetch mysql program status
  shell: >-
    {{ supervisor_bin_path }}/supervisorctl -c {{ supervisor_conf_path }} status {{ mysql_supervisor_program }}
  register: mysql_program_status

- name: Show mysql program status
  debug: var="mysql_program_status.stdout_lines"