- name: Stop ketadb - mysql
  supervisorctl:
    name: "{{ mysql_supervisor_program }}"
    state: stopped
    config: "{{ supervisor_conf_path }}"
    supervisorctl_path: "{{ supervisor_bin_path }}/supervisorctl"

- name: Wait for mysql stopping within 120s
  wait_for:
    port: "{{ mysql_run_port }}"
    state: drained
    timeout: 120