- include_tasks:
    file: install.yml
    apply:
      tags:
        - install
  tags:
    - install

- include_tasks:
    file: reread.yml
    apply:
      tags:
        - reread
  tags:
    - reread

- include_tasks:
    file: start.yml
    apply:
      tags:
        - start
  tags:
    - start

- include_tasks:
    file: restart.yml
    apply:
      tags:
        - restart
  tags:
    - restart

- include_tasks:
    file: status.yml
    apply:
      tags:
        - status
  tags:
    - status

- include_tasks:
    file: stop.yml
    apply:
      tags:
        - stop
  tags:
    - stop
