- name: Reread ketadb - mysql
  supervisorctl:
    name: ketadb_mysql
    state: present
    config: /home/{{ketadb_user}}/supervisor/supervisord.conf
    supervisorctl_path: /home/{{ketadb_user}}/.local/bin/supervisorctl
