- name: Check if ketadb is installed
  stat:
    path: "{{ ketadb_root_path }}/{{ ketadb_version }}/install.tag"
  register: ketadb_install_check

- name: Ensure ketadb not install
  fail: msg="Ketadb is installed."
  when: ketadb_install_check.stat.exists

- name: Ensure ketadb packages and workspace directory exists
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ ketadb_run_user }}"
    group: "{{ ketadb_run_user }}"
    recurse: yes
  loop:
    - "{{ ketadb_root_path }}"
    - "{{ ketadb_root_path }}/{{ ketadb_version }}"

- name: Copy ketadb install file into tmp directory
  copy:
    src: "{{ ketadb_install_file }}"
    dest: "/tmp/ketadb.install.file"

- name: Unarchive ketadb install file to workspace
  unarchive:
    src: "/tmp/ketadb.install.file"
    dest: "{{ ketadb_root_path }}/{{ ketadb_version }}"
    extra_opts: "--strip-components=1"
    remote_src: yes

- name: Touch the tag file for checking installed
  file:
    path: "{{ ketadb_root_path }}/{{ ketadb_version }}/install.tag"
    state: touch
