- name: Fetch ketadb program status
  shell: >-
    {{ supervisor_bin_path }}/supervisorctl -c {{ supervisor_conf_path }} status {{ ketadb_supervisor_program }}
  register: ketadb_program_status

- name: Show ketadb program status
  debug: var="ketadb_program_status.stdout_lines"
