- name: Stop ketadb
  supervisorctl:
    name: "{{ ketadb_supervisor_program }}"
    state: stopped
    config: "{{ supervisor_conf_path }}"
    supervisorctl_path: "{{ supervisor_bin_path }}/supervisorctl"

- name: Wait for ketadb stopping within 120s
  wait_for:
    port: "{{ ketadb_config_list['transport.tcp.port'] }}"
    state: drained
    timeout: 120
